### ISSUE TITLE
tyc2.bin missing

### ISSUE THREAD

**Issue by shrx** [Fingel/fchart#2]
I have installed `fchart` with `sudo pip install fchart`.
When I run `fchart m45` in terminal, I get:

```
fchart version 0.3 (c) 2005 Michiel Brentjens

fchart comes with ABSOLUTELY NO WARRANTY. It is distributed under the
GNU General Public License (GPL) version 2. For details see the LICENSE
file distributed with the software. This is free software, and you are
welcome to redistribute it under certain conditions as specified in the
LICENSE file.

Traceback (most recent call last):
  File "/usr/local/bin/fchart", line 310, in <module>
    starcatalog    = StarCatalog(data_dir+os.sep+'tyc2.bin', data_dir+os.sep+'index.dat')
  File "/usr/local/lib/python2.7/site-packages/fchart/star_catalog.py", line 92, in __init__
    print str(self.read_catalog(filename))+' stars loaded.'
  File "/usr/local/lib/python2.7/site-packages/fchart/star_catalog.py", line 111, in read_catalog
    num_bytes    = os.path.getsize(filename)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/fchart/data/catalogs/tyc2.bin'
```

Indeed, there is no `data` folder inside the `/usr/local/lib/python2.7/site-packages/fchart/` directory.
I am on OS X 10.10.3.

**Comment by shrx** [comment]
The fix is to download the source and manually place the `data` folder inside `/usr/local/lib/python2.7/site-packages/fchart/`.

**Comment by Fingel** [comment]
It looks like it was removed from PyPi. Probably because the file is so large. Better to just clone this repo and use setup.py
